"""phase4_context_versioning_overrides_reputation

Revision ID: 133a0e6fbe2c
Revises: 
Create Date: 2026-02-25 08:20:02.129142
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133a0e6fbe2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('eas', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_agent_name', 'agent', ['name'], unique=False)
    op.create_index('ix_agent_status', 'agent', ['status'], unique=False)
    op.create_table('policy_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('version_string', sa.String(length=255), nullable=False),
    sa.Column('policy_yaml', sa.Text(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_policy_version_created_at', 'policy_version', ['created_at'], unique=False)
    op.create_table('agent_policy_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('rule_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_agent_policy_override_active', 'agent_policy_override', ['is_active'], unique=False)
    op.create_index('ix_agent_policy_override_agent_id', 'agent_policy_override', ['agent_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('device_targets', sa.JSON(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('risk_tier', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requires_audit', sa.Boolean(), nullable=False),
    sa.Column('requires_senior_approval', sa.Boolean(), nullable=False),
    sa.Column('eas_at_time', sa.Float(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_log_tool_name', 'audit_log', ['tool_name'], unique=False)
    op.create_index('ix_audit_log_verdict', 'audit_log', ['verdict'], unique=False)
    op.create_table('eas_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eas_score', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_eas_history_agent_id', 'eas_history', ['agent_id'], unique=False)
    op.create_index('ix_eas_history_timestamp', 'eas_history', ['timestamp'], unique=False)
    op.create_table('escalation_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('risk_tier', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('device_targets', sa.JSON(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('requires_senior_approval', sa.Boolean(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_escalation_created_at', 'escalation_record', ['created_at'], unique=False)
    op.create_index('ix_escalation_status', 'escalation_record', ['status'], unique=False)
    op.create_table('execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('device_target', sa.String(length=255), nullable=False),
    sa.Column('command_sent', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('rollback_data', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_execution_log_device_target', 'execution_log', ['device_target'], unique=False)
    op.create_index('ix_execution_log_timestamp', 'execution_log', ['timestamp'], unique=False)
    op.create_index('ix_execution_log_tool_name', 'execution_log', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_log_tool_name', table_name='execution_log')
    op.drop_index('ix_execution_log_timestamp', table_name='execution_log')
    op.drop_index('ix_execution_log_device_target', table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index('ix_escalation_status', table_name='escalation_record')
    op.drop_index('ix_escalation_created_at', table_name='escalation_record')
    op.drop_table('escalation_record')
    op.drop_index('ix_eas_history_timestamp', table_name='eas_history')
    op.drop_index('ix_eas_history_agent_id', table_name='eas_history')
    op.drop_table('eas_history')
    op.drop_index('ix_audit_log_verdict', table_name='audit_log')
    op.drop_index('ix_audit_log_tool_name', table_name='audit_log')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_agent_policy_override_agent_id', table_name='agent_policy_override')
    op.drop_index('ix_agent_policy_override_active', table_name='agent_policy_override')
    op.drop_table('agent_policy_override')
    op.drop_index('ix_policy_version_created_at', table_name='policy_version')
    op.drop_table('policy_version')
    op.drop_index('ix_agent_status', table_name='agent')
    op.drop_index('ix_agent_name', table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
